from setuptools import setup

setup(
    name='chempionat_ru',
    version='1.0',
    packages=['venv37.Lib.site-packages.bs4', 'venv37.Lib.site-packages.bs4.tests',
              'venv37.Lib.site-packages.bs4.builder', 'venv37.Lib.site-packages.pip',
              'venv37.Lib.site-packages.pip._vendor', 'venv37.Lib.site-packages.pip._vendor.idna',
              'venv37.Lib.site-packages.pip._vendor.pep517', 'venv37.Lib.site-packages.pip._vendor.pytoml',
              'venv37.Lib.site-packages.pip._vendor.certifi', 'venv37.Lib.site-packages.pip._vendor.chardet',
              'venv37.Lib.site-packages.pip._vendor.chardet.cli', 'venv37.Lib.site-packages.pip._vendor.distlib',
              'venv37.Lib.site-packages.pip._vendor.distlib._backport', 'venv37.Lib.site-packages.pip._vendor.msgpack',
              'venv37.Lib.site-packages.pip._vendor.urllib3', 'venv37.Lib.site-packages.pip._vendor.urllib3.util',
              'venv37.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv37.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv37.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv37.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv37.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv37.Lib.site-packages.pip._vendor.colorama', 'venv37.Lib.site-packages.pip._vendor.html5lib',
              'venv37.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv37.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv37.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv37.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv37.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'venv37.Lib.site-packages.pip._vendor.lockfile', 'venv37.Lib.site-packages.pip._vendor.progress',
              'venv37.Lib.site-packages.pip._vendor.requests', 'venv37.Lib.site-packages.pip._vendor.packaging',
              'venv37.Lib.site-packages.pip._vendor.cachecontrol',
              'venv37.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv37.Lib.site-packages.pip._vendor.webencodings', 'venv37.Lib.site-packages.pip._vendor.pkg_resources',
              'venv37.Lib.site-packages.pip._internal', 'venv37.Lib.site-packages.pip._internal.cli',
              'venv37.Lib.site-packages.pip._internal.req', 'venv37.Lib.site-packages.pip._internal.vcs',
              'venv37.Lib.site-packages.pip._internal.utils', 'venv37.Lib.site-packages.pip._internal.models',
              'venv37.Lib.site-packages.pip._internal.commands', 'venv37.Lib.site-packages.pip._internal.operations',
              'venv37.Lib.site-packages.idna', 'venv37.Lib.site-packages.mysql',
              'venv37.Lib.site-packages.mysql.connector', 'venv37.Lib.site-packages.mysql.connector.django',
              'venv37.Lib.site-packages.mysql.connector.fabric', 'venv37.Lib.site-packages.mysql.connector.locales',
              'venv37.Lib.site-packages.mysql.connector.locales.eng', 'venv37.Lib.site-packages.certifi',
              'venv37.Lib.site-packages.chardet', 'venv37.Lib.site-packages.chardet.cli',
              'venv37.Lib.site-packages.urllib3', 'venv37.Lib.site-packages.urllib3.util',
              'venv37.Lib.site-packages.urllib3.contrib', 'venv37.Lib.site-packages.urllib3.contrib._securetransport',
              'venv37.Lib.site-packages.urllib3.packages', 'venv37.Lib.site-packages.urllib3.packages.backports',
              'venv37.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv37.Lib.site-packages.requests',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv37.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Ulenspiegel',
    author_email='',
    description='', install_requires=['beautifulsoup4']
)
